### ISSUE TITLE
Product Tax not working

### ISSUE THREAD

**Issue by vignates** [taxjar/taxjar-magento2-extension#10]
Hi,

We want to ignore tax for specific products in Magento by setting Tax Class to None. This is the default feature in Magento and it was working till we integrate TaxJar module. 

Steps to reproduce:
1. Goto product edit page in Magento admin
2. Change Tax Class to None for a product.
3. Save the product and place an order.

Expected result: Tax shouldn't be applied to that product
Actual result: Tax is applied for that product as well.

**Comment by fastdivision** [comment]
Hi @vignates,

Thanks for reporting this. You're right, we shouldn't be collecting sales tax on products with a tax class set to "None". I'll get this PR merged shortly to ensure we pass a `99999` exempt tax code.
