### ISSUE TITLE
Do not support multi tax accounts for multi store view?

### ISSUE THREAD

**Issue by michaeldyl520** [taxjar/taxjar-magento2-extension#12]
I wan't configure tax accounts for multi store view in magento,but,when I connected taxjar account in magento2 current store setting(for example `default store view`),it will return `default config` store view,how can i configed it?

**Comment by fastdivision** [comment]
Hi @michaeldyl520,

At this time our Magento extensions generally support one TaxJar account per Magento instance. We don't yet support store-specific nexus addresses under **Store > Nexus Addresses** and transaction sync filtered for multiple stores.

However, if you're only using TaxJar for sales tax calculations and you don't require multiple nexus addresses per TaxJar account, it's possible to change the API token for each store. Switch scopes to your store view, set `Debug Mode` to "Yes" and change the API token. You'll also want to update your shipping origin under **Store > Configuration > Shipping Settings** to be store-specific. You cannot use our nexus addresses feature with this approach, you can only populate the `from_` parameters using the shipping origin.

**Comment by mykhailo-superiorseating** [comment]
Any updates on this?
