### ISSUE TITLE
Wrong tax calculation if coupon code is applied

### ISSUE THREAD

**Issue by dusanmisic** [taxjar/taxjar-magento2-extension#123]
Hi,

### Description

We are experiencing wrong tax calculation on checkout - payment step. 
Issue reproduced on clean Magento 2.3.4 with sample data and TaxJar 1.4.9
There are more than one product in cart (in our example, we will show with one product - qty: 6). And if "Cart Price Rules" -> Coupon code is applied with Fixed amount discount (Discount Amount: $64) - tax is not calculated properly.

### Steps to Reproduce

1. Add one product item to cart 6 times (qty: 6) - ie. SKU: WJ12-XS-Black
2. Apply discount code: Fixed amount discount (Discount Amount: $64) > Actions - only for this SKU: WJ12-XS-Black
3. Go to checkout (payment step) and you will notice that Tax is improperly calculated.

### Expected Result
Cart Subtotal ($815.94)
Discount (Test - $64 off) (-$384.00)
Shipping ($20.41)
Tax ($37.32)

It should be calculated as:
Tax for items: ($815.94 -$384.00) => 8.25% (TX, USA) => $35.64
plus
Tax for shipping: ($20.41) => 8.25% (TX, USA) => $1.68
and it should be: $37.32

### Actual Result
Cart Subtotal ($815.94)
Discount (Test - $64 off) (-$384.00)
Shipping ($20.41)
Tax ($57.78)

### Versions
- Magento 2.3.4

#### What edition(s) of Magento did this issue happen on?
- Magento Open Source (CE)

#### What version of PHP did this issue happen on?
- PHP 7.3.x

Here are screenshots of our Tax setup from admin and Fronted results:

![01 - coupon](https://user-images.githubusercontent.com/7780766/79575841-ae081f00-80c2-11ea-8c26-3827a4d3ca7c.png)
![02 - tax-settings](https://user-images.githubusercontent.com/7780766/79575854-b19ba600-80c2-11ea-9797-1be578c40aeb.png)
![03 - checkout](https://user-images.githubusercontent.com/7780766/79576216-38e91980-80c3-11ea-8442-3c2d5f2899e0.png)

Can you check for this issue, because we are experiencing this issue on our Production website.

Thanks in advance,
Dusan

**Comment by ryanreeves-taxjar** [comment]
Hi @dusanmisic, I believe you encountered an error that was fixed in [PR 118](https://github.com/taxjar/taxjar-magento2-extension/pull/118).  Could you please update to the latest version of the TaxJar extension and try again?

**Comment by dusanmisic** [comment]
Hi @ryanreeves-taxjar,

Thank you for your efforts. This is exactly what we needed. It works as expected now.

Thanks once again,
Dusan
