### ISSUE TITLE
No tranasaction found when click on sync transcation

### ISSUE THREAD

**Issue by sunilit42** [taxjar/taxjar-magento2-extension#13]
Hello,

$statesToMatch = ['complete', 'closed'];

when i debug it query is 

SELECT `main_table`.* FROM `sales_order` AS `main_table` WHERE (`updated_at` >= '2017-09-11 00:00:00') AND (`updated_at` <= '2017-09-20 23:59:59') AND (`state` = 'complete') AND (`state` = 'closed')

It should be OR condition for state

**Comment by fastdivision** [comment]
Hi @sunilit42,

Which version of Magento 2 are you using? Here's what I'm seeing in the backfill process:

```php
$orderResult->printLogQuery(true);
```

```sql
SELECT `main_table`.* FROM `sales_order` AS `main_table` WHERE ((`updated_at` >= '2017-09-20 00:00:00')) AND ((`updated_at` <= '2017-09-20 23:59:59')) AND ((`state` = 'complete') OR (`state` = 'closed'))
```

**Comment by sunilit42** [comment]
We are using Magento 2.0.7

**Comment by sunilit42** [comment]
Taxjar\SalesTax\Model\Transaction

to buildToAddress function, 

 $toAddress = [
            'to_country' => $address->getCountryId(),
            'to_zip' => $address->getPostcode(),
            'to_state' => $address->getRegionCode(),
            'to_city' => $address->getCity(),
            'to_street' => $address->getData('street')
        ];
$address->getRegionCode() for me getting Georgia
it should ne 2 char.

**Comment by fastdivision** [comment]
@sunilit42 We require Magento 2.1+ for transaction sync. To perform a logical OR, we [specify multiple filters within a filter group](https://github.com/taxjar/taxjar-magento2-extension/blob/develop/Observer/BackfillTransactions.php#L181) correctly [based on the documentation](http://devdocs.magento.com/guides/v2.1/howdoi/webapi/search-criteria.html). In 2.0.7, there's [still some issues](https://github.com/magento/magento2/blob/2.0.7/app/code/Magento/Sales/Model/OrderRepository.php#L99) with the `getList` method and search criteria. Also, [`getRegionCode`](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Model/Order/Address.php#L121) underwent some changes between Magento 2.0.7 and 2.1.0.

**Comment by sunilit42** [comment]
@fastdivision 

thanks for your response, i already fixed in magento2.0.7 and working fine.

There is no cron for sync transaction everry day?

**Comment by fastdivision** [comment]
@sunilit42 No cron jobs at the moment for transaction sync, just for backup rates. We sync orders and their corresponding refunds immediately after the order is updated via [sales_order_save_after](https://github.com/taxjar/taxjar-magento2-extension/blob/develop/etc/adminhtml/events.xml#L26) in a `complete` or `closed` state. Older transactions can be imported into TaxJar using the **Sync Transactions** button.

**Comment by sunilit42** [comment]
seems like you created event only for admin area, sometime order complete using frontend side as well

so that event should be global.

**Comment by fastdivision** [comment]
@sunilit42 Can you provide an example of when Magento dispatches the `sales_order_save_after` event from a core module on the frontend? I'll investigate, thanks!

**Comment by sunilit42** [comment]
@fastdivision 

let's example virtal product on cart, and you are using online payment method, so after order place order status is complete.

**Comment by fastdivision** [comment]
Ah, that makes sense. I'll look into making this event global and test it out for virtual orders. Appreciate the help!

**Comment by sunilit42** [comment]
@fastdivision welcome :)

otherwise, remove event and make cron for synchronization order.

**Comment by fastdivision** [comment]
Thanks @sunilit42, moved that event to global for [v0.7.5](/taxjar/taxjar-magento2-extension/releases/tag/v0.7.5).
