### ISSUE TITLE
RFE: Transaction Sync Command

### ISSUE THREAD

**Issue by alloylab** [taxjar/taxjar-magento2-extension#14]
It would be great to be able to sync transaction to TaxJar via the command line to capture any missed transactions.

For example: bin/magento taxjar:sync

**Comment by fastdivision** [comment]
@alloylab I like this idea! We'd probably want to include some additional arguments to import date ranges or order IDs, otherwise fall back to the previous day. I'd also like to implement commands for syncing nexus addresses and backup rates.

I'll look into implementing this in the near future.

**Comment by alloylab** [comment]
@fastdivision i agree... maybe the following commands... 

bin/magento taxjar:rates;
bin/magento taxjar:nexus;

bin/magento taxjar:sync prev_day;
bin/magento taxjar:sync; defaults to bin/magento taxjar:sync prev_day
bin/magento taxjar:sync prev_week;
bin/magento taxjar:sync prev_month;
bin/magento taxjar:sync range 12/01/2016 to 12/31/2016;

**Comment by fastdivision** [comment]
Merged #19, this is ready to go!
