### ISSUE TITLE
Address not validated if postalcode is not filled in last

### ISSUE THREAD

**Issue by NickdeK** [taxjar/taxjar-magento2-extension#142]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description
When filling in the address fields and a user decides to fill in the address fields in a random order the validation doesn't show. This happens only when the postal code is entered before the other address fields. The default order of fields would usually prevent this, but when you change the order of the fields in a theme (or a user decides to use another order of entering the fields) the validation doesn't show at all in a normal flow except when you go back a step.

### Steps to Reproduce

1. Enter the postal code field first
2. Enter the other fields after the postal fields

### Expected Result
Address validation should happen on all field changes or (to prevent unnecessary API calls) only check when clicking the next button.

### Actual Result
Address validation happens on the next button call but the checkout still continues to the next step without the user seeing the possible invalid address warning from Taxjar.

### Versions

- [ ] Magento 2.4
- [x] Magento 2.3
- [ ] Magento 2.2
- [ ] Magento 2.1

- [x] Magento Open Source (CE)
- [ ] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [x] PHP 7.x
- [ ] PHP 5.x

**Comment by ryanreeves-taxjar** [comment]
Thanks for reporting this @NickdeK (and especially for the video)!  Could you let us know if you have any 3rd party checkout extensions installed?

**Comment by NickdeK** [comment]
Yes, quite a few, but disabling them still results in the above issues.

**Comment by sethobey** [comment]
Closed with acceptance of #182
