### ISSUE TITLE
Orders and Credit Memo admin grid pages break when using custom table prefix

### ISSUE THREAD

**Issue by leoquijano** [taxjar/taxjar-magento2-extension#145]
### Prerequisites

- [X] Are you running the latest version of our extension?
   Version 1.5.4

- [X] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?

- [X] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description

When using TaxJar on a Magento installation that uses a custom table prefix (i.e. tables are named like ```tj_sales_order``` instead of the default ```sales_order```), the admin pages for the orders and credit memos grid will break, with an error like the following:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento_db.sales_order' doesn't exist, query was: SELECT COUNT(*) FROM `tj_sales_order_grid` AS `main_table` LEFT JOIN `sales_order` ON main_table.entity_id = sales_order.entity_id
```

The issue is caused by a bug in ```\Taxjar\SalesTax\Plugin\AddTjSyncDateToGrid::afterGetReport```:

```
if ($collection instanceof OrderGridCollection) {
    $collection->getSelect()->joinLeft(
        'sales_order',
        'main_table.entity_id = sales_order.entity_id',
        'tj_salestax_sync_date'
    );
}

if ($collection instanceof CreditmemoGridCollection) {
    $collection->getSelect()->joinLeft(
        'sales_creditmemo',
        'main_table.entity_id = sales_creditmemo.entity_id',
        'tj_salestax_sync_date'
    );
}
```

The calls to ```joinLeft``` use the ```sales_order``` and ```sales_creditmemo``` table names directly, instead of calling the ```getTable()``` method to add the required prefix. The references to those tables should be passed to ```getTable``` as follows:

```
if ($collection instanceof OrderGridCollection) {
    $collection->getSelect()->joinLeft(
        ['sales_order' => $collection->getTable('sales_order')],
        'main_table.entity_id = sales_order.entity_id',
        'tj_salestax_sync_date'
    );
}

if ($collection instanceof CreditmemoGridCollection) {
    $collection->getSelect()->joinLeft(
        ['sales_creditmemo' => $collection->getTable('sales_creditmemo')]
        'main_table.entity_id = sales_creditmemo.entity_id',
        'tj_salestax_sync_date'
    );
}
```
    
### Steps to Reproduce

1. Setup TaxJar on a Magento instance that uses a table prefix (for example, ```tj``` above).
2. Try to load the orders admin page or the credit memos admin page.

### Expected Result

The page loads successfully.

### Actual Result

The page breaks with the error mentioned above.

### Versions

- [ ] Magento 2.4
- [X] Magento 2.3
- [ ] Magento 2.2
- [ ] Magento 2.1

- [X] Magento Open Source (CE)
- [ ] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [X] PHP 7.x
- [ ] PHP 5.x

**Comment by itecedor** [comment]
This also just happened to me and caused me to downgrade back down. I went from version 1.5.0 to 1.5.3 and admin sales grid failed to load due to SQL error: 

```
[2020-07-19 17:04:26] main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DB_NAME.sales_order' doesn't exist, query was: SELECT COUNT(*) FROM `DB_PREFIX_sales_order_grid` AS `main_table`
 LEFT JOIN `sales_order` ON main_table.entity_id = sales_order.entity_id [] []
```

Running 2.3.5-p1

**Comment by ryanreeves-taxjar** [comment]
Thanks for reporting this @leoquijano and @itecedor!  We'll be looking into this PR shortly.

**Comment by gxrobb** [comment]
We are experiencing the same issue, toggling taxjar off seems to fix it. We get the same error, no table prefix is shown when targeting the sales_order table.

**Comment by sandeep570** [comment]
Even I am facing the same issue when I try to filter with Order status. Any solution for this?

**Comment by ryanreeves-taxjar** [comment]
@sandeep570 @gxrobb @itecedor @leoquijano 

PR #148 addresses this issue and will be available in the next release.  If you choose to use it before the release, please feel free to share any feedback you have!

**Comment by sandeep570** [comment]
@ryanreeves-taxjar  I have fixed the issue as below and if it is ok I will use if not any better code please let me know.

--- a/vendor/taxjar/module-taxjar/Plugin/AddTjSyncDateToGrid.php	2020-08-06 17:57:00.915430210 +0530
+++ b/vendor/taxjar/module-taxjar/Plugin/AddTjSyncDateToGrid.php	2020-08-06 17:56:32.419483000 +0530
@@ -35,18 +35,20 @@
         $collection
     ) {
         if ($collection instanceof OrderGridCollection) {
+            $so = new \Zend_Db_Expr('(SELECT entity_id, tj_salestax_sync_date from '.$collection->getTable('sales_order').')');
             $collection->getSelect()->joinLeft(
-                'sales_order',
-                'main_table.entity_id = sales_order.entity_id',
-                'tj_salestax_sync_date'
+                ["so" => $so],
+                'main_table.entity_id = so.entity_id',
+                ['tj_salestax_sync_date' => 'so.tj_salestax_sync_date']
             );
         }
 
         if ($collection instanceof CreditmemoGridCollection) {
+            $scm = new \Zend_Db_Expr('(SELECT entity_id, tj_salestax_sync_date from '.$collection->getTable('sales_creditmemo').')');
             $collection->getSelect()->joinLeft(
-                'sales_creditmemo',
-                'main_table.entity_id = sales_creditmemo.entity_id',
-                'tj_salestax_sync_date'
+                ["scm" => $scm],
+                'main_table.entity_id = scm.entity_id',
+                ['tj_salestax_sync_date' => 'scm.tj_salestax_sync_date']
             );
         }

**Comment by sandeep570** [comment]
@ryanreeves-taxjar  I have fixed the issue as below and if it is ok I will use if not if u have any better code please let me know.

![Screenshot from 2020-08-06 21-04-43](https://user-images.githubusercontent.com/45820900/89551404-892de800-d828-11ea-84a9-11df33587887.png)

**Comment by ryanreeves-taxjar** [comment]
@sandeep570 I would recommend using PR #148
