### ISSUE TITLE
Error deleting nexus address

### ISSUE THREAD

**Issue by subbu1993** [taxjar/taxjar-magento2-extension#15]
## Preconditions
- Magento Version: 2.1.2
- TaxJar Version: 0.7.4
- PHP Version: 7.0.20-1~dotdeb+8.2
- PHP Memory Limit: 256M
- Backup States: FL
- Backup Last Updated: 10-02-2017

## Steps to reproduce
1) Delete an existing nexus address

## Expected result
1) Nexus address gets deleted
2) Backup rates have refreshed to not include counties from the deleted nexus address

## Actual result
1) An error message in the admin panel saying "Something went wrong deleting this nexus address."

![image](https://user-images.githubusercontent.com/13652158/31092642-14fbf064-a77d-11e7-9dd6-1baf800ac7e9.png)

I have debug logging on and nothing is currently being written to debug.log

## Additional notes: 

Updating (clicking the "Save nexus address button") an existing nexus address also throws an error saying "We can't save this nexus address right now."

**Comment by fastdivision** [comment]
@subbu1993 Thank you for the detailed report. Looks like an account-specific issue with our API. Can you send this info and your TaxJar account email to support@taxjar.com so I can take a closer look?

**Comment by subbu1993** [comment]
@fastdivision I have a support request open, I am closing this issue hence.

Thanks
