### ISSUE TITLE
Refunds not synced in TaxJar 

### ISSUE THREAD

**Issue by ilievski** [taxjar/taxjar-magento2-extension#16]
Refunds are not synced into TaxJar when creditmemo is created. 
When sales_order_save_after event is triggered on creditmemo creation in the observer SyncTransaction the order creditmemo collection is empty and refund is not synced to TaxJar.

**Comment by fastdivision** [comment]
@ilievski Are you on v0.7.4 or 0.7.5 of our extension?

**Comment by ilievski** [comment]
The module is updated to 0.7.5 but still cannot commit refund sync due to empty creditmemos collection. 
I think the problem comes from CreditmemoService class where the the event dispatch happens before transaction commit.

**Comment by fastdivision** [comment]
@ilievski Thank you for reporting this issue and I appreciate your patience. I'll release a fix shortly.
