### ISSUE TITLE
Unable to filter CreditMemo Grid by created_at date filter

### ISSUE THREAD

**Issue by danmentzer** [taxjar/taxjar-magento2-extension#161]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description

After Installing Taxjar extension credit memo grid can't be filtered by created at date.

### Steps to Reproduce

1. Go to the credit memo grid
2. Try and filter by a date.

### Expected Result
To filter the grid by the imposed date conditions

### Actual Result
Got a Ui component error saying something went wrong.
Checking the exception log we had this exception.

[2020-10-20 03:27:24] report.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous, query was: SELECT COUNT() FROM sales_creditmemo_grid AS main_table
LEFT JOIN sales_creditmemo AS creditmemos ON main_table.entity_id = creditmemos.entity_id WHERE (created_at >= '2020-10-01 04:00:00') AND (created_at <= '2020-10-20 03:59:59') {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous, query was: SELECT COUNT() FROM sales_creditmemo_grid AS main_table
LEFT JOIN sales_creditmemo AS creditmemos ON main_table.entity_id = creditmemos.entity_id WHERE (created_at >= '2020-10-01 04:00:00') AND (created_at <= '2020-10-20 03:59:59') at vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous at vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} []

### Versions

- [ ] Magento 2.4
- [x] Magento 2.3
- [ ] Magento 2.2
- [ ] Magento 2.1

- [x] Magento Open Source (CE)
- [x] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [x] PHP 7.x
- [ ] PHP 5.x

**Comment by ryanreeves-taxjar** [comment]
Hi @danmentzer.  Thanks for reporting this issue!  Could you please confirm the version of the TaxJar extension you're using?  I believe this issue was addressed in PR #148

**Comment by danmentzer** [comment]
Hi @ryanreeves-taxjar  Yes I can confirm the issue with using version 1.5.8 and version 1.5.7 and on both Magento 2 open source and Commerce.

I also can confirm that the commit you mentioned is there but both M2 sites have the same error when trying to apply any filter to the credit memo grid.

**Comment by danmentzer** [comment]
Hi @ryanreeves-taxjar 

I noticed you just released a new version of the taxjar extension anychance that fixes the issue I brought up?

**Comment by jkcr** [comment]
@danmentzer 

I do not believe this is fixed in version 1.6, which is the latest version as of the time of this writing.

I upgraded on staging, but issue persists. Disabling the tax jar plugin resolves the issue.

**Comment by jkcr** [comment]
I ran into this same issue working on another plugin, when trying to extend the grid, and there is a fairly simple fix. 

Most likely this would get placed in the Plugin/AddTjSyncDateToGrid.php file, although I haven't really looked at how tax jar is doing it. You could also add a simple di.xml override just for the creditmemo collection. 

`    protected function _construct(){
        $this->addFilterToMap('created_at', 'main_table.created_at');
}`

Note that this is different from the '__construct', it only has a single _

**Comment by fastdivision** [comment]
Fixed in #171

**Comment by khoimm92** [comment]
This need to reopen or open a new issue. I got the same error when filtering orders by date (on the sales grid).
Update: I opened a new issue here https://github.com/taxjar/taxjar-magento2-extension/issues/341
> Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous

**Comment by sethobey** [comment]
Hi @khoimm92, sorry to hear this issue has persisted for you! We will look into this and follow up
