### ISSUE TITLE
Suggested Address Not Working

### ISSUE THREAD

**Issue by joweecaquicla** [taxjar/taxjar-magento2-extension#168]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description

When the suggested address is selected in the checkout page, the selected goes back to the original address after all items.

### Steps to Reproduce

1. Add items to cart
2. Click the mini cart
3. Click checkout
4. See if there's a “suggested address”
5. If so, select the suggested address
6. Once “suggested address” is selected and the shipping methods and order summary have finished loading, the radio button selection for the Suggested Address jumps to the original address.
 
### Expected Result

The selected radio button on the Suggested Address would remain/not switch to the original address.

### Actual Result

The radio button selection for the Suggested Address jumps to the original address when the page finishes loading.

I also checked the `Taxjar_SalesTax/js/view/suggested_address_checkout_step.js ` file and modified some lines:
Line 86 from this:
```
subscribeToSuggestedAddesses: function () {
            var self = this;
            this.suggestedAddresses.subscribe(function (newValue) {
                console.log(newValue);
                self.suggestedAddressRadio(0);
                self.toggleDisplay();
            });
        },
```
to this:
```
subscribeToSuggestedAddesses: function () {
            var self = this;
            this.suggestedAddresses.subscribe(function (newValue) {
                self.suggestedAddressRadio();
                self.toggleDisplay();
            });
        },
```
This resolved the part where the selected address goes back to the original address, however, when I try to proceed to the payment page, the "Ship To" address (under the Order Summary section) still shows the original address. And if you select credit card or any payment method that will require a billing address and check the "same as shipping" checkbox, it shows the suggested address. When completing the checkout, only the billing address is updated, but the shipping address remains the same as the original address.

### Versions

- [ ] Magento 2.4
- [x] Magento 2.3
- [ ] Magento 2.2
- [ ] Magento 2.1

- [ ] Magento Open Source (CE)
- [x] Magento Commerce (EE)
- [x] Magento B2B
- [ ] Magento Cloud

- [x] PHP 7.x
- [ ] PHP 5.x

**Comment by sethobey** [comment]
Closed with acceptance of #182
