### ISSUE TITLE
'Please redeploy production mode' admin error shows even in production mode

### ISSUE THREAD

**Issue by rsamartino** [taxjar/taxjar-magento2-extension#170]
### Prerequisites

- [yes, 1.6.0 ] Are you running the latest version of our extension?
- [yes ] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?
- [yes ] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description
Navigating to the Sales > Tax configuration admin page shows the error 'Please redeploy production mode in the Magento CLI ($ bin/magento deploy:mode:set production) to ensure address validation works correctly.' even when the site is in production mode. This appears to be because the $prevEnabled variable here is a serialized value which will not match $enabled https://github.com/taxjar/taxjar-magento2-extension/blob/v1.6.0/Observer/ConfigReview.php#L138

This is happening with Magento Community Edition 2.4.1

### Steps to Reproduce

1. install Magento Community Edition 2.4.1
2. Install version 1.6.0 of the Taxjar module
3. set Magento to production mode
3. Navigate in the admin to Stores > Configuration > Sales > Tax

The error message will display

### Versions

- [X ] Magento 2.4
- [ ] Magento 2.3
- [ ] Magento 2.2
- [ ] Magento 2.1

- [X ] Magento Open Source (CE)
- [ ] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [X ] PHP 7.x (php 7.4)
![Configuration_Settings_Stores_Magento_Admin(2)](https://user-images.githubusercontent.com/25776875/105557330-34443800-5cc9-11eb-90e0-744112f06525.jpg)
[prev_enabled_value.txt](https://github.com/taxjar/taxjar-magento2-extension/files/5859061/prev_enabled_value.txt)
![Screenshot_20210122_153347](https://user-images.githubusercontent.com/25776875/105557335-35756500-5cc9-11eb-90b3-9fbe1987f6b9.png)

- [ ] PHP 5.x

**Comment by sethobey** [comment]
Hello @rsamartino 

Thank you for your reporting this issue! I was able to reproduce the bug that you describe and will prioritize a fix. In the meantime, it appears that refreshing the browser will set the cached values again, dismissing the notification.
