### ISSUE TITLE
Subtotal change after tax is applied - rounding to 2 decimal places not implemented

### ISSUE THREAD

**Issue by danac-gs** [taxjar/taxjar-magento2-extension#173]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description
Magento rounds prices to 2 decimal points, as documented here https://docs.magento.com/user-guide/tax/quick-reference.html
> Important! Changes have been made from earlier versions for EU merchants or other VAT merchants who display prices
> including tax and operate in several countries with multiple store views. If you load prices with more than two digits of
> precision, Magento automatically rounds all prices to two digits to ensure that a consistent price is presented to buyers.

and observed here https://github.com/magento/magento2/blob/2.4/app/code/Magento/Quote/Model/Quote/Item/AbstractItem.php#L407

On the contrary, TaxJar doesn’t do any rounding, as observed here
https://github.com/taxjar/taxjar-magento2-extension/blob/master/Model/Tax/TaxCalculation.php#L201

For instance, a product has a price of $32.66 and a tier discount (quantity 5 or more) of 10% which equals to $29,394. When calculating for quantity of 10, Magento calculation equals to $293.90 (rounded before multiplication):

![image](https://user-images.githubusercontent.com/37150717/108237911-ab45e280-7148-11eb-9d2c-5197cdb4eb6d.png)

But after triggering Taxjar (by entering an address) the subtotal becomes $293.94 (not rounded before multiplication).

![image](https://user-images.githubusercontent.com/37150717/108238020-cd3f6500-7148-11eb-951c-b9968f3e925b.png)

What TaxJar does is that, when in the total calculation pipeline, it rewrites the previous (subtotal) values generated by Magento.

This can cause problems with other plugins that rely on 2 decimal points rounding, as used and recommended by Magento.
It was encountered when trying to integrate Bolt Payment, https://github.com/BoltApp/bolt-magento2.

### Steps to Reproduce

1. Create a product with a price of $32.66.
2. Set up tier price discount of 10% when more than 5 items of this product are added to cart
3. Add 10 items to cart from a fresh guest session (or incognito window) 
4. Go to the shopping cart page and observe the cart subtotal. It is $293.90.
5. Trigger the tax calculation (estimate shipping and tax on the shopping cart page, or go to the default checkout page and complete the shipping step)
6. Observe the cart subtotal. Now it is $293.94.

### Expected Result
Tax calculation should not change cart subtotal. 

### Actual Result
Cart subtotal is changed.

### Versions
The issue is version agnostic.

**Comment by sethobey** [comment]
Acceptance of #178 closes this issue.
