### ISSUE TITLE
Magento 2.1.8 Fatal error:  Uncaught TypeError: Argument 3 passed TaxjarCommonTaxCollector::afterMapItem()

### ISSUE THREAD

**Issue by magemanish** [taxjar/taxjar-magento2-extension#174]
Hi

### Description
Magento 2.1.8 found issue when add to cart.

<b>Fatal error</b>:  Uncaught TypeError: Argument 3 passed 

### Expected Result
<b>Fatal error</b>:  Uncaught TypeError: Argument 3 passed to 
 Taxjar\SalesTax\Plugin\Tax\Model\Sales\Total\Quote\TaxjarCommonTaxCollector::afterMapItem() must be an instance of Magento\Tax\Api\Data\QuoteDetailsItemInterfaceFactory, none given, called in /home/thestampsoflife/public_html/sandbox/vendor/magento/framework/Interception/Interceptor.php on line 152 and defined in /home/thestampsoflife/public_html/sandbox/vendor/taxjar/module-taxjar/Plugin/Tax/Model/Sales/Total/Quote/TaxjarCommonTaxCollector.php:41
Stack trace:
#0 /home/thestampsoflife/public_html/sandbox/vendor/magento/framework/Interception/Interceptor.php(152): Taxjar\SalesTax\Plugin\Tax\Model\Sales\Total\Quote\TaxjarCommonTaxCollector-&gt;afterMapItem(Object(Magento\Tax\Model\Sales\Total\Quote\Subtotal\Interceptor), Object(Magento\Tax\Model\Sales\Quote\ItemDetails))
#1 /home/thestampsoflife/public_html/sandbox/var/generation/Magento/Tax/Model/Sales/Total/Quote/Subtotal/Interceptor.php(26): Magento\Tax\Model\Sales\Total\Quote\Subtotal\Interceptor-&gt;___callPlugins('mapIte in <b>/home/thestampsoflife/public_html/sandbox/vendor/taxjar/module-taxjar/Plugin/Tax/Model/Sales/Total/Quote/TaxjarCommonTaxCollector.php</b> on line <b>41</b><br />

### Steps to Reproduce
1. Add to cart show error.

### Versions

- [ ] Magento 2.1.8
- [ ] Magento Open Source (CE)
- [ ] PHP 7.0.33
- [ ]  TaxJar Version: 1.6.0

![issue](https://user-images.githubusercontent.com/25637016/108368333-55446e00-7220-11eb-8bb9-2305f5e6c4f0.png)

**Comment by sethobey** [comment]
Hello @magemanish,

I am closing this issue since it has been inactive for 9 months and I am unable to confirm or reproduce the bug that you describe. Please feel free to reopen this issue if you are able to provide more detail so that we may replicate the error.
