### ISSUE TITLE
How to pass custom total while sync

### ISSUE THREAD

**Issue by sunilit42** [taxjar/taxjar-magento2-extension#18]
Hello,

in our system some extra total line, how to pass and show on that taxjar?

otherwise, it is showing different total

**Comment by fastdivision** [comment]
Hi @sunilit42,

For additional fees you'd pass additional line items to our API in this method:

https://github.com/taxjar/taxjar-magento2-extension/blob/develop/Model/Transaction.php#L166

Here's how we add an extra line item:

https://github.com/taxjar/taxjar-magento2-extension/blob/develop/Model/Transaction.php#L219-L226

Does this answer your question? Are you using native / core functionality in Magento for extra totals that we need to directly support in our extension?

**Comment by sunilit42** [comment]
Thanks for help :)
