### ISSUE TITLE
Issue with tax price conversion (Canada).

### ISSUE THREAD

**Issue by syed-ziffity** [taxjar/taxjar-magento2-extension#185]
### Prerequisites

- [ ] I have used the latest version. (1.6.3)
- [ ] Yes I have review your integration gudide.
- [ ] Yes I have checked the issue already logged in the GitHub there is no issue related to price conversion.

### Description
ISSUE - The tax is NOT in line with the 13% tax set by TaxJar (Ontario N8W3T6 = 13% combined tax percentage)
the issue is occurring only when adding shipping or coupon codes with a sub total. I have cross verified with the tax jar log in debug mode. API response returns a proper value but after Canadian dollar, conversion shows wrong value.
![screenshot-mcprod traverscanada com-2021 05 19-11_44_13](https://user-images.githubusercontent.com/58301572/118764876-cfc07080-b897-11eb-9307-5e11d21e46fb.png)

### Steps to Reproduce

1. Enter a qty =3 of 57-113-252
2. Estimate Shipping/tax (Canada/Ontario/N8W3T6)
3. Subtotal = $157.46
4. Shipping (Express) = $34.95
5. Tax = $37.52 ?????
6. PROBLEM = $157.46 + $34.95 = $192.41  | $192.41 x .13 = $25.0133 (not #37.52)   |   $25.0133 x 1.5 = $37.52
SOLUTION The tax is reflecting a percentage on subtotal and shipping costs already listed in Canadian dollars... therefore the $25.0133 DOES NOT need to be multiplied by the US --> CA 1.5X multiplier

### Versions

- [ ] Magento 2.3

- [ ] Magento Cloud

- [ ] PHP 7.x

**Comment by sethobey** [comment]
Hello @syed-ziffity,

We have attempted to recreate this issue, but unfortunately cannot duplicate the described behavior. You can see in the screenshots below, that with either a single taxable product or multiple taxable products with discount, the tax amount calculated does resolve to the expected effective 13% tax rate.

![image](https://user-images.githubusercontent.com/47947793/148276780-6469b5a4-14c9-44dc-b9ad-fd0d3f809b7a.png)

![image](https://user-images.githubusercontent.com/47947793/148277388-6a619845-23c4-4497-b1ac-1993c31653d1.png)

For this reason, I'm closing this issue for now, but if you are still experiencing this error, please feel free to reopen with any additional details that may help us reproduce the error or reach out to our expert support team at support@taxjar.com!
