### ISSUE TITLE
Sync observers prevent transaction sync in cron or console environment

### ISSUE THREAD

**Issue by bheindl** [taxjar/taxjar-magento2-extension#190]
### Prerequisites

- Install taxjar module.
- Implement a cron or simple script, which updates many orders or creditmemos (e.g. to get updates from an erp system).

### Steps to Reproduce

When running this cron job or script the first order is updated regularly and transactions are synced to taxjar. But all subsequent orders and creditmemos are prevented from beeing transmitted due to a registry flag from preventing multiple transactions synced in a single php script call.

### Solution

Please make the registry key preventing this multiple transactions on a single script call id based:

Observer/SyncTransaction.php line 101:

Is:

````
if (!$this->registry->registry('taxjar_sync_' . $eventName)) {
    $this->registry->register('taxjar_sync_' . $eventName, true);
} else {
    return $this;
}
````

Should:

````
if (!$this->registry->registry('taxjar_sync_' . $eventName . '_' . $order->getId())) {
    $this->registry->register('taxjar_sync_' . $eventName . '_' . $order->getId(), true);
} else {
    return $this;
}
````

Same in Observer/SyncRefund.php

**Comment by sethobey** [comment]
Hello @bheindl,

Our most recent v1.8.0 release now includes the option to "force" transaction records to sync, either from the UI or CLI. This feature will bypass the existing registry flag check, which should allow you to avoid the scenario detailed above. Please give it a try, as I believe it will solve the problem you are facing!

Closing this issue for now, but please feel free to re-open or reach out if you find v1.8.0 does not resolve the issue on your end!
