### ISSUE TITLE
Allow for AMQP message queue configuration

### ISSUE THREAD

**Issue by lbajsarowicz** [taxjar/taxjar-magento2-extension#242]
## Prerequisites
- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://www.taxjar.com/guides/integrations/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description
TaxJar comes with MySQL queue type by default:
https://github.com/taxjar/taxjar-magento2-extension/blob/4ea5c89a3a14731c48cf7795ba981437ba348859/etc/queue_topology.xml#L3-L7
Due to the performance, observability and maintainability reasons, projects should be able to switch the MQ to AMQP.

### Steps to Reproduce
1. Install TaxJar extension
2. Configure `env.php` to change the connection for TaxJar queues to `amqp`
```php
    'queue' => [
        'topics' => [
            'taxjar.backup_rates.delete' => [
                'publisher' => 'amqp-magento'
            ],
            'taxjar.backup_rates.create' => [
                'publisher' => 'amqp-magento'
            ],
            'taxjar.transactions.sync' => [
                'publisher' => 'amqp-magento'
            ]
...

        'config' => [
            'publishers' => [
                'taxjar.backup_rates.delete' => [
                    'connections' => [
                        'amqp' => [
                            'name' => 'amqp',
                            'exchange' => 'magento',
                            'disabled' => false
                        ],
                        'db' => [
                            'name' => 'db',
                            'disabled' => true
                        ]
                    ]
                ],
                'taxjar.backup_rates.create' => [
                    'connections' => [
                        'amqp' => [
                            'name' => 'amqp',
                            'exchange' => 'magento',
                            'disabled' => false
                        ],
                        'db' => [
                            'name' => 'db',
                            'disabled' => true
                        ]
                    ]
                ],
                'taxjar.transactions.sync' => [
                    'connections' => [
                        'amqp' => [
                            'name' => 'amqp',
                            'exchange' => 'magento',
                            'disabled' => false
                        ],
                        'db' => [
                            'name' => 'db',
                            'disabled' => true
                        ]
                    ]
                ]
...
        'consumers' => [
            'taxjar.backup_rates.delete.consumer' => [
                'connection' => 'amqp'
            ],
            'taxjar.backup_rates.create.consumer' => [
                'connection' => 'amqp'
            ],
            'taxjar.transactions.sync.consumer' => [
                'connection' => 'amqp'
            ]
```
3. Execute `bin/magento queue:consumer:list`

### Expected Result
1. TaxJar queues should be listed,
2. All the messages should be stored in AMQP

### Actual Result
1. Consumer configuration is broken, as Magento is unable to recognize the rest of configuration. 

### Versions

- [x] Magento 2.4
- [ ] Magento 2.3

- [x] Magento Open Source (CE)
- [ ] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [x] PHP 7.4
- [ ] PHP 7.3

**Comment by sethobey** [comment]
Hi @lbajsarowicz,

I believe we only intended to support the MySQL-adapter configuration that is included in the extension, so no testing was done with RabbitMQ or the like for compatibility.

I am aware though that official docs recommend using AMQP whenever possible, so while I hesitate to speak for the team, we are likely open to any fully-tested submission which would allow for AMQP configuration. I'll leave this issue open for now to gauge interest. Thanks for your submission!

**Comment by sethobey** [comment]
Hello @lbajsarowicz!

Wanted to share a public update here. After reviewing with the team, we would like to implement the suggested functionality, and plan to prioritize this issue in the near future.

Thanks for submitting!
