### ISSUE TITLE
Magento 2.3.2 not supported in version 1.8.0

### ISSUE THREAD

**Issue by mikeastral** [taxjar/taxjar-magento2-extension#244]
### Prerequisites

- [ ] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://developers.taxjar.com/integrations/guides/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description

On Magento 2.3.2, PHP 7.2: after installing version 1.8.0, manually or by composer the Magento site is crashing.  It looks
like compilation is wrong.

![15600227758719](https://user-images.githubusercontent.com/71626655/154281575-204a4e1a-8982-46b2-ad25-e043f69fffa0.png)

However, when installing version 1.7.1, the installation doesn't show any error

![15600224370529](https://user-images.githubusercontent.com/71626655/154281945-c2f5103e-cf36-4d79-9bf6-0cd525506498.png)

### Steps to Reproduce

1. [First Step]
Install the module by composer or manually
2. [Second Step]
Go to the home page (or any URL), Magento will crash

### Expected Result
Magento site working normally on both front and back end after installing version 1.8.0

### Actual Result
Magento site crashes

### Versions

- [ ] Magento 2.4
- [x] Magento 2.3.2
- [ ] Magento 2.3

- [x] Magento Open Source (CE)
- [ ] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [ ] PHP 7.4
- [ ] PHP 7.3
- [x] PHP 7.2

**Comment by sethobey** [comment]
Hi @mikeastral, thanks for reporting! We had originally moved to deprecate v2.3 with end of active support, but since Adobe's recent announcement of extended security support for v2.3 into Q3 of this year, we plan to also extend our v2.3 compatibility with the next minor release.

I will update/close this issue once the next M2 v2.3.x-compatible release is available.

**Comment by sethobey** [comment]
Hello @mikeastral, our v1.9.0 release is out today and should resolve any 2.3-related incompatibilities. Thanks for reporting!

**Comment by mikeastral** [comment]
Thanks for your feedback, we just upgraded to v1.9.0
