### ISSUE TITLE
Taxjar charging shipping on 100% discount cart rule

### ISSUE THREAD

**Issue by treii28** [taxjar/taxjar-magento2-extension#26]
We want to extend a coupon to customers as part of a marketing promotion that gives them 100% off their cart for a single item. When the subtotal shows up in the cart, it shows $0 for all items and $0 for shipping but taxjar still seems to be charging tax on the fixed-rate cost of shipping. (the regular fixed rate would be $5, but the subtotal to the customer is $0. But the grand total is showing with the regional sales tax on the shipping cost. e.g. for Michigan it is $0.06 on the dollar so it will show $0.30 as the total in the cart)

**Comment by treii28** [comment]
Hmm, when I was looking at those places in the code, I was going by the suggestions of your support that changing those lines (or more specifically, your support referred primarily to the Smartcalcs line 161 and 162) would change the result in the cart for the shipping. However, after I sent the suggestion I went about making the changes and deploying them here locally and it doesn't actually do anything to change the results in the cart.  It still ends up with a total of $0.30 so I assume the original suggestion to change that line was flawed.
The fix does not appear to resolve the problem.

**Comment by treii28** [comment]
As an aside, I also noticed that at that point in the code, the 'getGrandTotal' function is also returning the $5 shipping amount (without the discount applied) if the coupon code has been added to the cart. As in if I remove the coupon code, the getGrandTotal function will return Product cost + shipping cost + product tax + shipping tax.  If I apply the product code, getGrandTotal only returns the shipping cost. So I also opened a ticket on the main magento thread as this struck me as odd. I might understand it returning shipping in both instances if tax wasn't applied since there is a getShippingDiscountAmount() method, but tax (including shipping tax) is applied if there's no coupon applied to the cart.
[https://github.com/magento/magento2/issues/15673](url)

**Comment by fastdivision** [comment]
Hi @treii28, I tested this fix locally and added a couple specs to verify that discounts applied to shipping will be passed on to our API. After applying the code, can you try clearing your checkout session to verify the tax isn't cached on your end? If you're still encountering issues, can you share screenshots of your discount cart rule from admin so I can try to reproduce? Thank you!

**Comment by treii28** [comment]
well not only am I still showing the tax on the last page, now if I go back a page, it gets stuck in a loop or something in the javascript trying to calculate the shipping and crashes the browser (chrome) tab.  And if I open it in firefox, I get the shipping calculation repeating down the page over and over and over and over when it finally stops the code.

**Comment by treii28** [comment]
hmmm, ok, I'll have to do more testing. I made the modifications in place and it was causing all those problems. So I pulled your separate branch to a different folder and copied the whole thing, re-ran setup:upgrade and setup:di:compile and I think it's working now.

**Comment by treii28** [comment]
Hmmm, ok, it seems to work but still trying to nail down what all needs to be flushed to make it work. I had trouble getting it to go away this time also. I hope I don't have to clear every single customer cart to get it functioning properly.

**Comment by fastdivision** [comment]
@treii28 Glad that it's working now! When [caching API requests](https://github.com/taxjar/taxjar-magento2-extension/blob/80578434039de18caa0c810297902b7843ecead1/Model/Smartcalcs.php#L192), we set `taxjar_salestax_order` in the customer's checkout session with the complete order details. After applying the fix, customers that already have the shipping discount applied should have a different `shipping` amount when making a request. We'll determine that the order details have changed and hopefully make a new request with the updated `shipping` amount.

If you notice any caching issues with incoming orders after deploying the fix, you could consider commenting out the [`orderChanged` conditional](https://github.com/taxjar/taxjar-magento2-extension/blob/80578434039de18caa0c810297902b7843ecead1/Model/Smartcalcs.php#L186) temporarily until customer cookies expire after the fix goes live, depending on your configured [cookie lifetime](https://docs.magento.com/m2/ce/user_guide/customers/customer-online-options.html).

**Comment by treii28** [comment]
I don't think it's going to be a huge problem as we have a limited number of coupons of this sort in circulation and currently that's the first coupon we've issued as it's a new site. But good to know for future reference. Is there any way of being notified when this is added to master?  I get errors/warnings now due to the modified code base whenever running git on my own master.

**Comment by fastdivision** [comment]
@treii28 I'll try to get #27 merged and released by next week. Refactored some of the code today. I'll close out this issue once it's done. Thanks for your patience!
