### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by webcreative24** [taxjar/taxjar-magento2-extension#319]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://developers.taxjar.com/integrations/guides/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description
Please Fix the compatibility bug with PHP 8.1

### Steps to Reproduce

1. Crate new order from Admin
2. Press Submit button

### Expected Result
Order created

### Actual Result
Error appear:
Deprecated Functionality: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /vendor/taxjar/module-taxjar/Observer/SaveOrderMetadata.php on line 78

### Versions

- [x] Magento 2.4
- [ ] Magento 2.3

- [+] Magento Open Source (CE)
- [ ] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [ ] PHP 7.4
- [ ] PHP 7.3
- [x] PHP 8.1

**Comment by sethobey** [comment]
Hi @webcreative24, thanks for reporting! I was able to verify the bug and plan to get the fix out as soon as possible.

**Comment by sethobey** [comment]
@webcreative24 This issue should now be resolved by upgrading to v1.9.6. Thank you again for reporting!
