### ISSUE TITLE
Improvement to Postcode Validation

### ISSUE THREAD

**Issue by beechyrb** [taxjar/taxjar-magento2-extension#322]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://developers.taxjar.com/integrations/guides/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description
We have had multiple instances where customers bypassed the tax calculation at the checkout by adding a space before a postcode like this " 90230". The TaxJar API supports spaces however the `_validatePostcode` function in the "Model/Smartcalcs.php" file does not support the space and therefore skips tax calculations. We have had a patch on this function for a few years now to trim the postcode entered by the customer and it seems to be working fine. I would suggest this be added by default as I don't believe there are any countries that have postcodes with a space at the beginning or the end.

### Steps to Reproduce

1. Add an item to the cart and proceed to checkout, choose checkout as a guest for ease of replication.
2. Add a taxable US address and add a space before the postcode, Magento will complain but allow you to proceed.

### Expected Result
For the tax to be calculated on the order

### Actual Result
Tax calculations are skipped due to failing the `_validatePostcode` function

### Versions

- [x] Magento 2.4
- [x] Magento 2.3

- [ ] Magento Open Source (CE)
- [x] Magento Commerce (EE)
- [x] Magento B2B
- [x] Magento Cloud

- [x] PHP 7.4
- [x] PHP 7.3

**Comment by sethobey-stripe** [comment]
Hi @beechyrb, thanks for reporting this issue! We'll take a look.

**Comment by sethobey** [comment]
@beechyrb We were able to reproduce the issue and have implemented the fix you've described. It will be included in our next patch release v1.9.7. Thank you again for contributing!
