### ISSUE TITLE
API Version 2022-01-24

### ISSUE THREAD

**Issue by woodja** [taxjar/taxjar-magento2-extension#336]
### Prerequisites

- [X] Are you running the latest version of our extension?
- [X] Have you reviewed our [integration guide](https://developers.taxjar.com/integrations/guides/magento2/)?
- [X] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description
We received an email alerting us that API version 2020-08-07 is no longer supported, but that appears to be the version supported by this module. Will there be a newer version released before the August 31st deadline?

> Beginning August 31, 2022, the API will be upgraded for all TaxJar users. It’s important you take the time before then to add logic and test your configuration to prevent service interruptions by taking the following steps before August 31:
> 
> Pass the following HTTP request header for your custom TaxJar API integration:
> Code: "x-api-version: 2022-01-24"
> 

Code in question
https://github.com/taxjar/taxjar-magento2-extension/blob/develop/Model/Configuration.php#L59

### Steps to Reproduce
1. Install latest version of this module
2. Review the request headers and see it isn't compliant with this request

### Expected Result
`x-api-version: 2022-01-24`

### Actual Result
`x-api-version: 2020-08-07`

### Versions

- [ ] Magento 2.4
- [X] Magento 2.3

- [X] Magento Open Source (fka Magento 2 Community Edition)
- [ ] Adobe Commerce (fka Magento 2 Enterprise Edition)

- [ ] PHP 8.2
- [ ] PHP 8.1
- [ ] PHP 7.4
- [X] PHP 7.3

**Comment by sethobey** [comment]
@woodja - Thank you for taking the time to report this issue. No need to fear though, our API is backwards compatible, so requests will continue to succeed when passing previous versions in the header.

Looking into the upcoming API version changes, we found that updates primarily involve product tax code validation. Since our extension already restricts product tax code input, we wouldn't realize much benefit from the changes, but may address this in a future release.

**Comment by woodja** [comment]
@sethobey Thanks for the clarification and quick reply. We got quite the do or die email this week. It would have been helpful if it included a list of deprecated and discontinued API versions rather than saying we had to upgrade to the latest version.

**Comment by sethobey** [comment]
I'm terribly sorry for the miscommunication on our part @woodja! I hope it hasn't caused too much disruption on your end and I'll be sure to pass your feedback along to our team responsible for those communications.
