### ISSUE TITLE
Error when filtering Order grid by date

### ISSUE THREAD

**Issue by khoimm92** [taxjar/taxjar-magento2-extension#341]
### Prerequisites

- [x] Are you running the latest version of our extension?
- [x] Have you reviewed our [integration guide](https://developers.taxjar.com/integrations/guides/magento2/)?
- [x] Did you search through [existing issues](https://github.com/taxjar/taxjar-magento2-extension/issues)?

### Description

Can't filter the orders by Purchase date.

### Steps to Reproduce
1. Go to the sales order page
2. Try filter by a purchase date

### Expected Result
The result will be shown without any errors

### Actual Result
There was an error, the grid keeps infinity loading.
The log says:
> Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous

### Versions

- [x] Magento 2.4
- [ ] Magento 2.3

- [x] Magento Open Source (fka Magento 2 Community Edition)
- [ ] Adobe Commerce (fka Magento 2 Enterprise Edition)

- [ ] PHP 8.2
- [x] PHP 8.1
- [ ] PHP 7.4
- [ ] PHP 7.3

**Comment by sethobey** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/47947793/191549102-97a7ac82-ce64-4af3-b0b7-4a90453e61d3.png">
