### ISSUE TITLE
Magento 2.2 support

### ISSUE THREAD

**Issue by djamps** [taxjar/taxjar-magento2-extension#349]
It appears Magento 2.2.x not supported?   Is there any workaround?

bash-4.1$ bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 74.5 MiBPHP Fatal error:  Interface 'Magento\Framework\Setup\Patch\DataPatchInterface' not found in /var/www/html_mage2/app/code/Taxjar/SalesTax/Setup/Patch/Data/ImportTaxCategoriesPatch.php on line 11

Fatal error: Interface 'Magento\Framework\Setup\Patch\DataPatchInterface' not found in /var/www/html_mage2/app/code/Taxjar/SalesTax/Setup/Patch/Data/ImportTaxCategoriesPatch.php on line 11

**Comment by saville-stripe** [comment]
Hey @djamps,

Magento 2.2 reached end-of-life around three years ago. The only option to continue using an unsupported version of Magento would be to require the TJ extension @ v1.6.5 or earlier.

**Comment by djamps** [comment]
Thank you!
