### ISSUE TITLE
Magento 2.4.6

### ISSUE THREAD

**Issue by saderra** [taxjar/taxjar-magento2-extension#358]
On Magento 2.4.6, we are getting errors with nearly all functions, including: 

[2023-04-05T05:10:15.488661+00:00] main.CRITICAL: Error: Class "Zend_Http_Client" not found in /vendor/taxjar/module-taxjar/Model/Client.php:155. It's also preventing shipping rates from being calculated, invoices being created, refunded, etc... 

Please make Magento 2.4.6 compliant.

**Comment by petemcw** [comment]
I'm also running into this same issue on a new 2.4.6 project. Does anyone know how active the development team is on this extension?

**Comment by saderra** [comment]
Really hoping they resolve this soon. I've received dozens of messages from others with the same issue. This plugin is not compatible with Magento 2.4.6.

**Comment by saderra** [comment]
Hey TaxJar People: Here's how to fix

https://magento.stackexchange.com/questions/365470/class-zend-http-client-not-found-magento-2-4-6

**Comment by dzdaniel** [comment]
Hi TaxJar,

I'm getting the same issue, it's blocking us to upgrade to magento 2.4.6. Please help us to fix it ASAP.

Thanks!

**Comment by aohlrogge** [comment]
We are also having the same issue and it's preventing us from upgrading to Magento 2.4.6

**Comment by knowgod** [comment]
The similar issue we have in our Magento 2.4.6 instance. I was able to apply a workaround to eliminate the initial issue with missing library.
Then another issue comes out:
> Exception #0 (Exception): User Deprecated Functionality: Class is deprecated in /var/www/html/vendor/magento/framework/HTTP/ZendClient.php on line 27
> <pre>#1 trigger_error() called at [vendor/magento/framework/HTTP/ZendClient.php:27]
> #2 Magento\Framework\HTTP\ZendClient->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
> #3 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
> #4 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
> #5 Magento\Framework\ObjectManager\ObjectManager->create() called at [generated/code/Magento/Framework/HTTP/ZendClientFactory.php:43]
> #6 Magento\Framework\HTTP\ZendClientFactory->create() called at [vendor/taxjar/module-taxjar/Model/Smartcalcs.php:182]
> #7 Taxjar\SalesTax\Model\Smartcalcs->getTaxForOrder() called at [vendor/magento/framework/Interception/Interceptor.php:58]
> #8 Taxjar\SalesTax\Model\Smartcalcs\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
> #9 Taxjar\SalesTax\Model\Smartcalcs\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
> #10 Taxjar\SalesTax\Model\Smartcalcs\Interceptor->___callPlugins() called at [generated/code/Taxjar/SalesTax/Model/Smartcalcs/Interceptor.php:23]
> #11 Taxjar\SalesTax\Model\Smartcalcs\Interceptor->getTaxForOrder() called at [vendor/taxjar/module-taxjar/Model/Tax/Sales/Total/Quote/Tax.php:144]
> #12 Taxjar\SalesTax\Model\Tax\Sales\Total\Quote\Tax->collect() called at [generated/code/Taxjar/SalesTax/Model/Tax/Sales/Total/Quote/Tax/Interceptor.php:23]
> #13 Taxjar\SalesTax\Model\Tax\Sales\Total\Quote\Tax\Interceptor->collect() called at [vendor/magento/module-quote/Model/Quote/TotalsCollector.php:261]
> #14 Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals() called at [vendor/magento/module-quote/Model/Quote/TotalsCollector.php:156]
> #15 Magento\Quote\Model\Quote\TotalsCollector->collect() called at [vendor/magento/module-quote/Model/Quote.php:2021]

Hey, module maintainer, you really need to update your product.

**Comment by saderra** [comment]
@sethobey-stripe Any plans to get your module current with Magento 2.4.6?

**Comment by scottbolasevich** [comment]
ya wondering same

**Comment by rangerz** [comment]
For temp patch in here https://gist.githubusercontent.com/rangerz/5ec3b1aa8df34f8c15ce617d902d5d57/raw/edec1fbcc773aecda0b9bceca462235829a440cd/TaxJar-RemoveZend.patch

Its PR is in https://github.com/taxjar/taxjar-magento2-extension/pull/362

Only for Magento 2.4.6 and above, (for using `Magento\Framework\HTTP\LaminasClient`)

**Comment by fahu** [comment]
Thank you very much @rangerz ! It's a shame from TaxJar that here is still no update.

@ryanreeves-taxjar

**Comment by rangerz** [comment]
I reported the issue to TaxJar customer service.

I got the response as follows
> Thank you for your interest in TaxJar's Magneto plugin. I understand that you are seeking information about its compatibility with Magneto version 2.4.6, and I would be happy to assist you here.
> 
> To address your concern, I have created an engineering ticket specifically for our team responsible for TaxJar integrations. This ticket has been accepted by the engineering team, and they are currently in the process of assigning it to a sprint.
> 
> In our development process, an engineering sprint is a predetermined timeframe during which our engineering team focuses on completing a specific set of tasks. Typically, sprints last about two weeks, allowing our developers to prioritize small, incremental changes rather than larger, more complex ones. This approach enables us to deliver updates and improvements in a more streamlined manner, reducing the need for extensive debugging and ensuring a smoother experience for our clients.
> 
> At this stage, we are unable to provide you with an exact timeline or specify which sprint the engineering ticket will be assigned to. However, please be assured that our engineering team is actively working on resolving any compatibility issues with Magneto version 2.4.6. Once the necessary changes are implemented, we will promptly update our Magneto documentation to reflect the updates made to the plugin.
> 
> We appreciate your patience and understanding throughout this process. If you have any further questions or require additional assistance, please do not hesitate to reach out. We are here to help.

In short, they are aware, so please wait patiently...

**Comment by fahu** [comment]
@rangerz Thanks! I also raised it with their customer support, I guess the more people raise it the earlier it will get done..

**Comment by icecactus** [comment]
Same issue here :(

**Comment by saderra** [comment]
I saw an email from Magento a week or two ago saying they are removing all extensions from their Marketplace that aren't 2.4.6 compliant. So it sounds like TaxJar is possibly ending Magento support?

**Comment by rangerz** [comment]
Let's keep watching.
https://commercemarketplace.adobe.com/taxjar-module-taxjar.html
The deadline is Thursday, July 12th, 2023

**Comment by smolentzov-stripe** [comment]
Hi all, thank you for your patience. This should now be compatible with 2.4.6 with the latest update (v2.2.0).

**Comment by saderra** [comment]
With this update, you cannot save customers in Magento Admin. It gives this error: 

`[2023-07-26T17:12:15.188870+00:00] main.CRITICAL: Error: Call to a member function getValue() on null in /var/www/mage/vendor/taxjar/module-taxjar/Observer/Customer/Save.php:55
Stack trace:
#0 /var/www/mage/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Taxjar\SalesTax\Observer\Customer\Save->execute()
#1 /var/www/mage/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#2 /var/www/mage/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#3 /var/www/mage/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#4 /var/www/mage/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php(360): Magento\Framework\Event\Manager\Proxy->dispatch()
#5 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Adminhtml\Index\Save->execute()
#6 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent()
#7 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#8 /var/www/mage/generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php(23): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins()
#9 /var/www/mage/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->execute()
#10 /var/www/mage/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#11 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#12 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent()
#13 /var/www/mage/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#14 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#15 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#16 /var/www/mage/generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php(32): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins()
#17 /var/www/mage/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->dispatch()
#18 /var/www/mage/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#19 /var/www/mage/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#20 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#21 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#22 /var/www/mage/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#23 /var/www/mage/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#24 /var/www/mage/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#25 /var/www/mage/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#26 /var/www/mage/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#27 /var/www/mage/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#28 {main} {"exception":"[object] (Error(code: 0): Call to a member function getValue() on null at /var/www/mage/vendor/taxjar/module-taxjar/Observer/Customer/Save.php:55)"} []`
