### ISSUE TITLE
Cron Error

### ISSUE THREAD

**Issue by seavenger** [taxjar/taxjar-magento2-extension#4]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Taxjar\SalesTax\Observer\ImportRates::execute() must be an instance of Magento\Framework\Event\Observer, none given, called in /httpdocs/vendor/taxjar/module-taxjar/Observer/ImportRates.php on line 208 and defined in /httpdocs/vendor/taxjar/module-taxjar/Observer/ImportRates.php:166
Stack trace:
#0 /httpdocs/vendor/taxjar/module-taxjar/Observer/ImportRates.php(208): Taxjar\SalesTax\Observer\ImportRates->execute()
#1 [internal function]: Taxjar\SalesTax\Observer\ImportRates->cron(Object(Magento\Cron\Model\Schedule))
#2 /httpdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(247): call_user_func_array(Array, Array)
#3 /httpdocs/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(195): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob(1475308800, 1475308802, Array, Object(Magento\Cron\Model\Schedule),  in /httpdocs/vendor/taxjar/module-taxjar/Observer/ImportRates.php on line 166

**Comment by fastdivision** [comment]
@seavenger Thanks for reporting this! I'll get it fixed today and push out a new version.
