### ISSUE TITLE
Incorrect property name: Smartcalcs.php line 230

### ISSUE THREAD

**Issue by glo-arandazzo** [taxjar/taxjar-magento2-extension#40]
FYI - the reference to $this->_logger() on line 230 of Taxjar\SalesTax\Model\Smartcalcs is incorrect. 

It should use $this->logger().

Thanks,

Adam

**Comment by ryanreeves-taxjar** [comment]
Thanks for reporting this @glo-arandazzo.  We should have a fix out soon!

**Comment by fastdivision** [comment]
Fixed in #42
