### ISSUE TITLE
Magento Cloud EE Blank Config Page

### ISSUE THREAD

**Issue by beechyrb** [taxjar/taxjar-magento2-extension#44]
After installing and configuring TaxJar on Magento Cloud EE we are getting a blank page on the Tax Configuration page. Locally in our development environment it works fine.
![screenshot 2018-11-28 17 22 37](https://user-images.githubusercontent.com/7995987/49186447-b24b6500-f332-11e8-828e-c2e75305cdd5.png)

**Comment by ryanreeves-taxjar** [comment]
Thanks @beechyrb we'll take a look into this.  Could you please confirm the version of Magento you're using?

**Comment by beechyrb** [comment]
Magento Version 2.2.5

**Comment by EmilyPepperman** [comment]
We had a similar issue on our community site, it ended up being other extension conflicts. Try disabling Vertex and Dotmailers extensions if you are not using them ... they ship with 2.2.5

**Comment by ryanreeves-taxjar** [comment]
Hi @beechyrb, I'm unable to reproduce this issue on a vanilla installation of Magento Cloud.  

If you're still experiencing trouble, could you email our support team at [support@taxjar.com](mailto:support@taxjar.com)?  Please mention this issue in the email and we can continue with more in depth troubleshooting.
