### ISSUE TITLE
module.xml is not being updated

### ISSUE THREAD

**Issue by treii28** [taxjar/taxjar-magento2-extension#47]
It appears the module.xml shows the current version of any branch to be v1.0.0

**Comment by ryanreeves-taxjar** [comment]
Hi @treii28,

Thanks for taking the time to look through our codebase; we appreciate all the help we can get!  However I think you may be confusing the composer.json version with the setup_version found in module.xml.  

By browsing through older tags of this repository, you can see that the composer.json version does upgrade with each new release.  Here's an example from the 1.1.0 tag:  https://github.com/taxjar/taxjar-magento2-extension/blob/v1.1.0/composer.json

The schema_version in module.xml matches our current database schema.  We only update that version when we need to trigger new Setup scripts.  When we went from v0.6.4 to v0.7.0, we updated the schema_version to 0.7.0 to trigger the new UpgradeSchema.  

https://github.com/taxjar/taxjar-magento2-extension/blob/v0.7.0/etc/module.xml
https://github.com/taxjar/taxjar-magento2-extension/blob/v0.7.0/Setup/UpgradeSchema.php
