### ISSUE TITLE
Getting exception trying to logout from customer account

### ISSUE THREAD

**Issue by treii28** [taxjar/taxjar-magento2-extension#48]
Magento v2.2.4 running in Apache 2 on centos 7 with php 7.1

Tried with v1.0.3 and latest v1.1.1

When a customer is logged in and goes to log out, an exception is generated which seems to involve taxjar for some reason:

`1 exception(s): Exception #0 (Zend_Http_Exception): Invalid header line detected Exception #0 (Zend_Http_Exception): Invalid header line detected #0 /home/envystag/public_html/vendor/magento/zendframework1/library/Zend/Http/Response.php(696): Zend_Http_Response::extractHeaders('HTTP/2 200 rnco...') #1 /home/envystag/public_html/vendor/magento/zendframework1/library/Zend/Http/Client.php(1110): Zend_Http_Response::fromString('HTTP/2 200 rnco...') #2 /home/envystag/public_html/vendor/magento/framework/HTTP/ZendClient.php(52): Zend_Http_Client->request('POST') #3 /home/envystag/public_html/vendor/taxjar/module-taxjar/Model/Smartcalcs.php(218): MagentoFrameworkHTTPZendClient->request('POST') #4 /home/envystag/public_html/vendor/taxjar/module-taxjar/Model/Tax/Sales/Total/Quote/Tax.php(124): TaxjarSalesTaxModelSmartcalcs->getTaxForOrder(Object(MagentoQuoteModelQuoteInterceptor), Object(MagentoTaxModelSalesQuoteQuoteDetailsInterceptor), Object(MagentoQuoteModelShippingAssignmentInterceptor)) #5 /home/envystag/public_html/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(265): TaxjarSalesTaxModelTaxSalesTotalQuoteTax->collect(Object(MagentoQuoteModelQuoteInterceptor), Object(MagentoQuoteModelShippingAssignmentInterceptor), Object(MagentoQuoteModelQuoteAddressTotal)) #6 /home/envystag/public_html/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(144): MagentoQuoteModelQuoteTotalsCollector->collectAddressTotals(Object(MagentoQuoteModelQuoteInterceptor), Object(MagentoQuoteModelQuoteAddressInterceptor)) #7 /home/envystag/public_html/vendor/magento/module-quote/Model/Quote.php(1959): MagentoQuoteModelQuoteTotalsCollector->collect(Object(MagentoQuoteModelQuoteInterceptor)) #8 /home/envystag/public_html/vendor/magento/module-quote/Model/Quote.php(2392): MagentoQuoteModelQuote->collectTotals() #9 /home/envystag/public_html/vendor/magento/module-quote/Model/Quote.php(875): MagentoQuoteModelQuote->_afterLoad() #10 /home/envystag/public_html/vendor/magento/module-quote/Model/QuoteRepository.php(215): MagentoQuoteModelQuote->loadByCustomer('24') #11 /home/envystag/public_html/vendor/magento/module-quote/Model/QuoteRepository.php(134): MagentoQuoteModelQuoteRepository->loadQuote('loadByCustomer', 'customerId', '24', Array) #12 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(58): MagentoQuoteModelQuoteRepository->getForCustomer('24', Array) #13 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MagentoQuoteModelQuoteRepositoryInterceptor->___callParent('getForCustomer', Array) #14 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MagentoQuoteModelQuoteRepositoryInterceptor->MagentoFrameworkInterception{closure}('24', Array) #15 /home/envystag/public_html/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php(39): MagentoQuoteModelQuoteRepositoryInterceptor->___callPlugins('getForCustomer', Array, Array) #16 /home/envystag/public_html/vendor/magento/module-quote/Model/QuoteRepository.php(159): MagentoQuoteModelQuoteRepositoryInterceptor->getForCustomer('24', Array) #17 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(58): MagentoQuoteModelQuoteRepository->getActiveForCustomer('24') #18 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MagentoQuoteModelQuoteRepositoryInterceptor->___callParent('getActiveForCus...', Array) #19 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MagentoQuoteModelQuoteRepositoryInterceptor->MagentoFrameworkInterception{closure}('24') #20 /home/envystag/public_html/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php(65): MagentoQuoteModelQuoteRepositoryInterceptor->___callPlugins('getActiveForCus...', Array, Array) #21 /home/envystag/public_html/vendor/magento/module-checkout/Model/Session.php(247): MagentoQuoteModelQuoteRepositoryInterceptor->getActiveForCustomer('24') #22 /home/envystag/public_html/vendor/magento/module-checkout/Model/Session.php(416): MagentoCheckoutModelSession->getQuote() #23 /home/envystag/public_html/vendor/magento/module-checkout/Observer/UnsetAllObserver.php(33): MagentoCheckoutModelSession->clearQuote() #24 /home/envystag/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): MagentoCheckoutObserverUnsetAllObserver->execute(Object(MagentoFrameworkEventObserver)) #25 /home/envystag/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): MagentoFrameworkEventInvokerInvokerDefault->_callObserverMethod(Object(MagentoCheckoutObserverUnsetAllObserver), Object(MagentoFrameworkEventObserver)) #26 /home/envystag/public_html/vendor/magento/framework/Event/Manager.php(66): MagentoFrameworkEventInvokerInvokerDefault->dispatch(Array, Object(MagentoFrameworkEventObserver)) #27 /home/envystag/public_html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): MagentoFrameworkEventManager->dispatch('customer_logout', Array) #28 /home/envystag/public_html/vendor/magento/module-customer/Model/Session.php(467): MagentoFrameworkEventManagerProxy->dispatch('customer_logout', Array) #29 /home/envystag/public_html/vendor/magento/module-customer/Controller/Account/Logout.php(80): MagentoCustomerModelSession->logout() #30 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(58): MagentoCustomerControllerAccountLogout->execute() #31 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MagentoCustomerControllerAccountLogoutInterceptor->___callParent('execute', Array) #32 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MagentoCustomerControllerAccountLogoutInterceptor->MagentoFrameworkInterception{closure}() #33 /home/envystag/public_html/generated/code/Magento/Customer/Controller/Account/Logout/Interceptor.php(26): MagentoCustomerControllerAccountLogoutInterceptor->___callPlugins('execute', Array, Array) #34 /home/envystag/public_html/vendor/magento/framework/App/Action/Action.php(107): MagentoCustomerControllerAccountLogoutInterceptor->execute() #35 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(58): MagentoFrameworkAppActionAction->dispatch(Object(MagentoFrameworkAppRequestHttp)) #36 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MagentoCustomerControllerAccountLogoutInterceptor->___callParent('dispatch', Array) #37 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MagentoCustomerControllerAccountLogoutInterceptor->MagentoFrameworkInterception{closure}(Object(MagentoFrameworkAppRequestHttp)) #38 /home/envystag/public_html/generated/code/Magento/Customer/Controller/Account/Logout/Interceptor.php(39): MagentoCustomerControllerAccountLogoutInterceptor->___callPlugins('dispatch', Array, Array) #39 /home/envystag/public_html/vendor/magento/framework/App/FrontController.php(55): MagentoCustomerControllerAccountLogoutInterceptor->dispatch(Object(MagentoFrameworkAppRequestHttp)) #40 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(58): MagentoFrameworkAppFrontController->dispatch(Object(MagentoFrameworkAppRequestHttp)) #41 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(138): MagentoFrameworkAppFrontControllerInterceptor->___callParent('dispatch', Array) #42 /home/envystag/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): MagentoFrameworkAppFrontControllerInterceptor->MagentoFrameworkInterception{closure}(Object(MagentoFrameworkAppRequestHttp)) #43 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(135): MagentoStoreAppFrontControllerPluginRequestPreprocessor->aroundDispatch(Object(MagentoFrameworkAppFrontControllerInterceptor), Object(Closure), Object(MagentoFrameworkAppRequestHttp)) #44 /home/envystag/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): MagentoFrameworkAppFrontControllerInterceptor->MagentoFrameworkInterception{closure}(Object(MagentoFrameworkAppRequestHttp)) #45 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(135): MagentoPageCacheModelAppFrontControllerBuiltinPlugin->aroundDispatch(Object(MagentoFrameworkAppFrontControllerInterceptor), Object(Closure), Object(MagentoFrameworkAppRequestHttp)) #46 /home/envystag/public_html/vendor/magento/framework/Interception/Interceptor.php(153): MagentoFrameworkAppFrontControllerInterceptor->MagentoFrameworkInterception{closure}(Object(MagentoFrameworkAppRequestHttp)) #47 /home/envystag/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): MagentoFrameworkAppFrontControllerInterceptor->___callPlugins('dispatch', Array, NULL) #48 /home/envystag/public_html/vendor/magento/framework/App/Http.php(135): MagentoFrameworkAppFrontControllerInterceptor->dispatch(Object(MagentoFrameworkAppRequestHttp)) #49 /home/envystag/public_html/vendor/magento/framework/App/Bootstrap.php(256): MagentoFrameworkAppHttp->launch() #50 /home/envystag/public_html/index.php(39): MagentoFrameworkAppBootstrap->run(Object(MagentoFrameworkAppHttpInterceptor)) #51 {main}
`

**Comment by ryanreeves-taxjar** [comment]
Hi @treii28,

Thanks for reporting this issue.  This is actually a problem with the Magento 2 framework not properly supporting HTTP/2 requests.  We've opened several issues with Magento to address this specifically:

- [https://github.com/magento/magento2/issues/19441](https://github.com/magento/magento2/issues/19441)
- [https://github.com/magento/magento2/issues/19442](https://github.com/magento/magento2/issues/19442)

Because you're using a version of cURL that supports HTTP/2, any request to TaxJar via Magento's Zend Curl Client will fail.  The tax recalculation is being triggered because the cart changed when logging out.  

In order to help you resolve this error, we'll need specific details about your hosting setup that aren't appropriate for a public forum.  Please contact our support team at support@taxjar.com, reference this issue along with your TaxJar account email and we'll help you to get this problem sorted!
