### ISSUE TITLE
Error when issuing partial refund with 0 qty set for all products

### ISSUE THREAD

**Issue by crankycyclops** [taxjar/taxjar-magento2-extension#56]
If you have transaction sync enabled in the taxjar module and issue a credit memo with all product qty's set to 0 and a non-zero adjustment refund, the taxjar module throws an error. My guess is that it's trying to sync the refund to Taxjar so it can update the transaction, and this is what's causing the error, but I'm not sure.

Steps to reproduce:

1. Log into the admin after completing a successful order
2. Go to Sales -> Orders
3. Click on a completed order
4. Click on Invoices on the left
5. Locate the relevant invoice and click on Action -> View
6. Click on "Credit Memo"
7. Set the qty of all products to refund to 0
8. Set Adjustment Refund to a non-zero value
9. Click Update Totals
10. Click Refund

Expected result: The refund should be issued and no errors are produced.
Actual result: the refund does go through, but the taxjar module throws an error:

`Notice: Undefined index: line_items in vendor/taxjar/module-taxjar/Model/Transaction/Refund.php on line 77
`

**Comment by ryanreeves-taxjar** [comment]
Hi @crankycyclops, thanks for reporting this.  

Could you please confirm which version of the extension you're running?  We recently pushed a fix for this which should resolve the issue you're encountering.

**Comment by crankycyclops** [comment]
1.1.1, installed via composer. I'll wait for the next release then :) Thank you!
