### ISSUE TITLE
multiple refunds for the same order shipping issue

### ISSUE THREAD

**Issue by dorgan** [taxjar/taxjar-magento2-extension#59]
When doing multiple credit memos on a single order subsequent credit memos contain full qty's of the product refunded, but only include the shipping that was refunded for that specific credit memo.

**Comment by dorgan** [comment]
inside of `Model/Transaction.php` instead of 
`$lineItem['quantity'] = (int) $orderItem->getQtyRefunded()`
I believe you really want:
`$lineItem['quantity'] = (int)$item->getQty();`

Which gets the qty included in the refund, not the total qty refunded for the order.

**Comment by ryanreeves-taxjar** [comment]
Thanks for reporting this @dorgan!  We are going to test this internally and update this thread with our results.

**Comment by ryanreeves-taxjar** [comment]
Opened PR https://github.com/taxjar/taxjar-magento2-extension/pull/102 to address this.

**Comment by ryanreeves-taxjar** [comment]
Closing this issue now that PR #102 has been merged.
