### ISSUE TITLE
not all transactions synced

### ISSUE THREAD

**Issue by AdminLinenStore** [taxjar/taxjar-magento2-extension#64]
I did transaction sync in the period (from / to ) and compare with transactions that results from magento2 backend from the same period of time then I compared transaction/order number one by one. Apparently the order number from taxjar download file is skipped from time to time (randomly). which mean some transactions in that period did not get synced. I did a numerous time resync the transactions ( from backend or even CLI command). They never synced the missing transaction. I thought I could use this data to calculate our sales tax but it's too way off.

**Comment by AdminLinenStore** [comment]
Magento Version: 2.2.1
TaxJar Version: 1.1.0
PHP Version: 7.0.32-1~dotdeb+8.1
PHP Memory Limit: 1024M
Backup States: NY
Backup Last Updated: 06-01-2019

**Comment by ryanreeves-taxjar** [comment]
Hello @AdminLinenStore.  We only sync transactions that are in a "complete" or "closed" state.  If you find that orders in "complete" or "closed" state still aren't syncing, could you please contact our support team at support@taxjar.com?

**Comment by AdminLinenStore** [comment]
Hi, I found out that transactions that customer address states and zipcode dont match will not sync (e.g. use enter Maryland as states and put zipcode from Massachusetts) we don't have zipcode/states check integrated on our store yet so that can happen. 

Thank you!

**Comment by ryanreeves-taxjar** [comment]
Thanks @AdminLinenStore.  If there is anything else we can help with please don't hesitate to reach out again!
