### ISSUE TITLE
Javascript issue in checkout prevents proceeding to billing step

### ISSUE THREAD

**Issue by FerihumF** [taxjar/taxjar-magento2-extension#73]
Hello,

so we had the situation on our production system, where customers were not able to proceed to the billing step in checkout, because input validation on the region field failed.

As I digged in to it, I found out that the shipping.js script is using the shipping address data from the quote to overwrite input data before the quote is actually updated with the input data, thus resulting in unselecting whatever state/region you selected. That may sound weird, but here an exact example how to reproduce the issue:

1) Add a product to the cart
2) Go to checkout
3) Enter email, name, street, city, zip-code in this order. Then select whatever country, only important that the country has mandatory state/region dropdown (e.g. US). After selecting the US, the input field for state/region should be empty. Now select a state and try to proceed to the billing step by clicking "Next".
4) The state/region field is now empty again and saying "This is a required field".

The problem is, that in _view/frontend/web/js/view/shipping.js_ in the function **setShippingAddressForm**, input data is overwritten with outdated quote data, as already stated above. Why is is outdated? Quote address data gets updated on some occasions, which include:
- Asynchronously after country/zip-code change (to update shipping methods)
- On clicking "Next" in the function **validateShippingInformation** in _Magento_Checkout/js/view/shipping.js_

Neither of these events apply to the case I stated above. The last field updated was the state/region field, which does not trigger the asynchronous process. In your **validateShippingInformation** function, you call **this._super()** only after the call to **setShippingAddressForm**.

The question now is: why is the function **setShippingAddressForm** even necessary. If it is, the validateShippingInformation function should be reconsidered, maybe like this:

```
validateShippingInformation: function () {
    if (this._super()) {
        this.setShippingAddressForm();
        return true;
    }
    return false;
}
```

I hope the issue is clear :)

Greetings from Austria,
Fabian

**Comment by ryanreeves-taxjar** [comment]
Hi @FerihumF, thanks for reporting this!  We're going to take a deeper look into this issue and will follow-up with our findings.

**Comment by ryanreeves-taxjar** [comment]
HI @FerihumF, thanks again for your help with reporting and troubleshooting this issue.  We've addressed the bug in this PR:  https://github.com/taxjar/taxjar-magento2-extension/pull/74
