### ISSUE TITLE
Unit testing: Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by uabassguy** [taxjar/taxjar-magento2-extension#77]
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in vendor/taxjar/module-taxjar/Test/Unit/GetterSetterTest.php on line 22

PHPUnit 6.5.14
Magento 2.3.2
PHP 7.2.20 (cli)

PHPUnit 6.x is now namespaced, recommended approach going forward is to change this to PHPUnit\Framework\TestCase

PR open here, please review and if possible add it to a new tagged release
https://github.com/taxjar/taxjar-magento2-extension/pull/76

**Comment by fastdivision** [comment]
Resolved in #76
