### ISSUE TITLE
Doesn't work when $eavAttribute->getDefaultFrontendLabel() is null

### ISSUE THREAD

**Issue by elfeffe** [taxjar/taxjar-magento2-extension#84]
When I go to Sales - Tax I get a white screen.
And error log says we are trying to setLabel on null.
Seems to be a problem with some attribute, and I think it's this one customer.custom.mgs_social_fid

PHP message: PHP Fatal error: Uncaught TypeError: Argument 1 passed to Vertex\Tax\Model\FlexField\FlexFieldProcessableAttribute::setLabel() must be of the type string, null given

**Comment by elfeffe** [comment]
This is the problem

$eavAttribute->getDefaultFrontendLabel()

Sometimes that returns null, and the extension doesn't work at all.
Not related to 2.3.3, but a bug

**Comment by ryanreeves-taxjar** [comment]
Thanks for reporting this issue @elfeffe.  We'll take a look into it and let you know what we find!

**Comment by alex91ckua** [comment]
Temporary fix:
`UPDATE eav_attribute set frontend_label='' WHERE frontend_label is NULL;`

**Comment by sumeet-synergytop** [comment]
@elfeffe  @ryanreeves-taxjar 
how to fix this issues ?
i am also getting this error -  Uncaught TypeError: Argument 1 passed to Vertex\Tax\Model\FlexField\FlexFieldProcessableAttribute::setLabel() must be of the type string, null given

**Comment by ryanreeves-taxjar** [comment]
@elfeffe @sumeet-synergytop It looks like that error is originating in the Vertex extension.  Could you please try disabling that extension to see if it resolves the error?

**Comment by sumeet-synergytop** [comment]
@ryanreeves-taxjar 
Okay
If we are disabling vertex extension then what about vertex functionality?

**Comment by ryanreeves-taxjar** [comment]
@sumeet-synergytop  We don't recommend using Vertex concurrently with our extension.  If you have additional questions around this, please email our support team at support@taxjar.com.

**Comment by elfeffe** [comment]
I don’t use Vertex, this is very easy to say “we don’t recommend using
Vertex with our extension”, instead of fixing the problem, you just do as
if it doesn’t exist.
Your code is not good, you should fix it as we did in our system, a
beginner can fix it in 10 minutes and make your extension compatible with
others.
I never used Vertex, so I use some other extension with the same problem.
But I know your solution “we don’t recommend using
###WRITETHENAMEOFTHEOTHEREXTENSIONHERE### with our extension”.
Very amateur.

**Comment by fastdivision** [comment]
@elfeffe Can you elaborate on the fix you used here specifically in the TaxJar extension? The error appears to come from the Vertex extension, which is bundled into Magento core. Please review the [patch](https://github.com/magento/magento2/issues/25403#issuecomment-557253300) provided in this [issue](https://github.com/magento/magento2/issues/25403):

> ```diff
> Index: vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php	(revision 21bce02860fb6a0661f434dc38527664aaa7dded)
> +++ vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php	(date 1574367021765)
> @@ -119,7 +119,7 @@
>              $attribute = $this->attributeFactory->create();
>              $attributeCode = $prefix . '.' . $eavAttribute->getAttributeCode();
>              $attribute->setAttributeCode($attributeCode);
> -            $attribute->setLabel($eavAttribute->getDefaultFrontendLabel());
> +            $attribute->setLabel($eavAttribute->getDefaultFrontendLabel() ?: $eavAttribute->getAttributeCode());
>              $attribute->setOptionGroup(__($optionGroup)->render());
>              $attribute->setType($type);
>              $attribute->setProcessor($processor);
> ```
> 
> If anyone using Vertex as their calculation engine needs a fix. Disabling the module also works well if you are not using Vertex as your calculation engine.
> 
> A fully tested and proper fix should be included with Magento 2.3.4

**It appears this issue was fixed in v3.0.0 of the Vertex module bundled in Magento 2.3.4.**

Thank you!
