### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by elfeffe** [taxjar/taxjar-magento2-extension#89]
I'm trying to issue a Credit Memo for an unshipped order.
I create it leaving default Magento data, it says 1 in qty to refund.
The customer bought a configurable product, with a simple of course.
When I save, it throws "Division by Zero" error on this line
`$lineItem['unit_price'] = $orderItem->getAmountRefunded() / $lineItem['quantity']`

For some reason this line
`$lineItem['quantity'] = (int) $orderItem->getQtyRefunded();`
Returns zero, I'm not sure if it's because it's not yet shipped.
In any case, the Credit Memo is created, but it throws this error, and TaxJar is not updated, so I still pay the taxes for that order.

**Comment by elfeffe** [comment]
When $type is refund
`if ($type == 'refund' && method_exists($item, 'getOrderItem')) {`

This is the $lineItem
```
array:7 [▼
  "id" => "247"
  "quantity" => 0
  "product_identifier" => "xxxxxxx"
  "description" => "xxxxxxx"
  "unit_price" => 595.0
  "discount" => 59.5
  "sales_tax" => 0.0
]
```

Quantity is 0, I think you are missing some IF there.
I can't believe that nobody is reporting this, or this is a problem related to the latest Magento, or there is a lot of people seeing that message and paying more taxes because of this.

**Comment by ryanreeves-taxjar** [comment]
Addressed in this PR:  https://github.com/taxjar/taxjar-magento2-extension/pull/99

**Comment by ryanreeves-taxjar** [comment]
This PR has been merged into the 'develop' branch and will be included in our next release.  Thanks @elfeffe!
