### ISSUE TITLE
Taxjar randomically not calculating taxes on checkout

### ISSUE THREAD

**Issue by FabioMasala** [taxjar/taxjar-magento2-extension#92]
We are experiencing a problem on the checkout page. Randomly it happens that when we land on the checkout page the total is calculated without taxes. 

This is the case when sometimes this happens:
- user is logged in
- the user already has a valid address previously saved
- virtual product on cart
- the taxes are calculated based on billing address

If we update the address even without modifying it the taxes are correctly calculated.

Do you have any idea why the taxes are not calculated on first place?

We are using Magento 2.3.3 with taxjar 1.4.4

**Comment by ryanreeves-taxjar** [comment]
Thanks @FabioMasala, we'll take a look into this issue and let you know what we find!

**Comment by FabioMasala** [comment]
@ryanreeves-taxjar thank you for your response.

**Comment by APanteleychuk** [comment]
I think it happens then the customer address(State) not added in nexus address. I have this problem too.

**Comment by ryanreeves-taxjar** [comment]
Hi @APanteleychuk!  Can you please [enable debugging mode](https://www.taxjar.com/guides/integrations/magento2/#debug-mode) and confirm there are no errors being logged?  If you continue to experience issues, please feel free to email our support team at support@taxjar.com.

**Comment by ryanreeves-taxjar** [comment]
I'm still unable to recreate this issue.  If anyone can provide step-by-step instructions to recreate it I'd be happy to reopen it!
