### ISSUE TITLE
Multi-line street address validation

### ISSUE THREAD

**Issue by dani97** [taxjar/taxjar-magento2-extension#97]
Customer address with two street lines are not validated by taxjar address validation
I examined the code and found https://github.com/taxjar/taxjar-magento2-extension/blob/bdbc45ce804506d358552ebf610f00acedf194aa/view/base/web/js/model/address_validation_core.js#L45 doesn't send all street lines to taxjar service. I created a mixin and sent the value. Found taxjar webapi ignoring extra street lines and fixed that too.

After fixing both, my address validation for test addresses failed which were validated correctly without the fix.

**Comment by ryanreeves-taxjar** [comment]
Thanks @dani97.  We'll take a look at this in a future release and let you know what we find!

**Comment by ryanreeves-taxjar** [comment]
Hi @dani97.  We have some technical limitations that prevent supporting multiple streets at this time.  We're working on some internal changes to better support this and I'll update again once those changes are completed.  Thanks for your patience and stay tuned!

**Comment by sethobey** [comment]
Hello @dani97,

Unfortunately, due to API limitations, it appears that we are still unable to implement the requested multi-line street address validation feature in our Taxjar_SalesTax extension. I'm going to close this issue for now, but thank you for your submission!
